---
deployment:
  tasks:
    - export DEPLOYPATH=/home/petervan/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R webfonts $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH 
    - /bin/cp -R styles $DEPLOYPATH